update rpi v2 camera iqfile and okdo 5mp iqfile
radxa-pkg/rockchip-iqfiles pull request #12
Opened 2023-10-30 11:37 UTC by Ken-Vamrs

2023-11-01 02:28 UTC, RadxaYuntian requested changes

2023-11-01 02:28 UTC, RadxaYuntian commented on rockchip-iqfiles/imx219_rpi-camera-v2_default.xml
怎么直接删了

2023-11-02 02:17 UTC, RadxaYuntian reviewed
另外没有[ov5647_rpi-camera-v1p3_default.xml](https://github.com/radxa-pkg/rockchip-iqfiles/blob/main/rockchip-iqfiles/ov5647_rpi-camera-v1p3_default.xml)对应的json profile么？

2023-11-02 02:17 UTC, RadxaYuntian commented on rockchip-iqfiles/imx219_rpi-camera-v2_default.xml
这个文件的换行符好像有问题，能格式化一下么？

2023-11-02 06:47 UTC, Ken-Vamrs commented
> 另外没有[ov5647_rpi-camera-v1p3_default.xml](https://github.com/radxa-pkg/rockchip-iqfiles/blob/main/rockchip-iqfiles/ov5647_rpi-camera-v1p3_default.xml)对应的json profile么？

我们3588系列只送调试了OKDO 5MP摄像头，和树莓派v1.3应该是共用的

2023-11-02 06:50 UTC, RadxaYuntian commented
那处理一下换行符问题吧

2023-11-02 07:21 UTC, Ken-Vamrs commented
> 那处理一下换行符问题吧

之前的估计也是格式的问题, 重新推了

2023-11-02 07:22 UTC, RadxaYuntian approved these changes

2023-11-02 07:22 UTC, merged