update imx219 files for 3280*2464 resolutio
radxa-pkg/rockchip-iqfiles pull request #17
Opened 2024-03-05 03:52 UTC by Radxa-Alvin

2024-03-05 03:59 UTC, RadxaYuntian approved these changes
rk356x版本没有更新

2024-03-05 04:00 UTC, RadxaYuntian requested changes
需要包含rk356x的profile

2024-03-05 04:39 UTC, Radxa-Alvin commented
356X系列用的另外一个内核分支 还没做支持，先提交3399和3588系列的文件

2024-03-13 12:00 UTC, RadxaYuntian commented
radxa/kernel#282 合并了

2024-03-13 12:01 UTC, RadxaYuntian approved these changes

2024-03-13 12:01 UTC, RadxaYuntian commented
resolutio少了个n，改一下，不然生成changelog是会报错

2024-03-15 10:08 UTC, RadxaYuntian approved these changes

2024-03-15 10:08 UTC, merged