feat: packaged rockchip-iqfiles-rk2312
radxa-pkg/rockchip-iqfiles pull request #21
Opened 2024-04-15 11:57 UTC by CodeChenL

2024-04-15 12:03 UTC, CodeChenL commented
@RadxaYuntian request a review

2024-04-15 12:09 UTC, RadxaYuntian requested changes

2024-04-15 12:09 UTC, RadxaYuntian commented on debian/control
> +Description: Additional camera tuning profiles for Rockchip SDK released in Dec. '23
```suggestion
Description: Additional camera tuning profiles for Rockchip kernel rk2312
```

2024-04-15 12:09 UTC, RadxaYuntian commented on debian/rockchip-iqfiles-rk2312.postinst
> +		do
这个缩进是不是有点不对

2024-04-16 03:25 UTC, CodeChenL commented on debian/rockchip-iqfiles-rk2312.postinst
> +		do
直接copy的rk356x的文件，用的是制表符，需要换成空格吗

2024-04-16 07:01 UTC, RadxaYuntian commented on debian/rockchip-iqfiles-rk2312.postinst
> +		do
都换了吧，我们应该大部分缩进都是用空格

2024-04-16 07:27 UTC, RadxaYuntian requested changes
rebase一下，格式修改的单独一个commit,然后再是添加新的包

2024-04-16 07:32 UTC, RadxaYuntian approved these changes

2024-04-16 07:32 UTC, merged